#version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_NAME: "sadicweb.blabla.com"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/server.crt:/etc/nginx/ssl/server.crt
      - ./nginx/server.key:/etc/nginx/ssl/server.key
      - ./sadicweb/static:/opt/static_root
    depends_on:
      - sadicweb

  sadicweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sadicweb
    privileged: true
    environment:
      DEBUG: "True"
      DJANGO_SUPERUSER_USERNAME: "superuser"
      DJANGO_SUPERUSER_EMAIL: "mail@mail.example"
      DJANGO_SUPERUSER_PASSWORD: "password"
      PROJECT_ROOT: "/opt"
      SECRET_KEY: "klajsfkljasdfkljasdfkljadsfjklads"
      DATABASE_HOST: 'sadic_database'
      DATABASE_PORT: 3306
      DATABASE_NAME: 'sadic'
      DATABASE_USER: 'sadic'
      DATABASE_PASSWORD: 'nomoresecret'
      DB_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"         
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    

  mariadb:
    privileged: true
    image: mariadb:latest
    container_name: sadic_database
    environment:
      MYSQL_ROOT_PASSWORD: nomoresecret
      MYSQL_DATABASE: sadic
      MYSQL_USER: sadic
      MYSQL_PASSWORD: nomoresecret
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  mariadb_data:      