"""
Django settings for sadic project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ
from split_settings.tools import optional, include
from sadicweb.config.env import ENV, PROJECT_ROOT


sadic_configs = [
    'base.py',
    'database.py',
]

# Local settings overrides
local_configs = [
    # Local settings relative to coldfront.config package
    'local_settings.py',

    # System wide settings for production deployments
    '/etc/sadicweb/local_settings.py',

    # Local settings relative to coldfront project root
    PROJECT_ROOT('local_settings.py')
]

if ENV.str('SADIC_CONFIG', default='') != '':
    # Local settings from path specified via environment variable
    local_configs.append(environ.Path(ENV.str('SADIC_CONFIG'))())

for lc in local_configs:
    sadic_configs.append(optional(lc))

include(*sadic_configs)



