# Generated by Django 5.1.5 on 2025-01-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDBInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdb_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "pdb_file",
                    models.FileField(blank=True, null=True, upload_to="pdb_files/"),
                ),
            ],
        ),
    ]
